const testWithFixture = require("./fixtureUtils/testWithFixture")

describe("addition", () => {
  test("add.rock converted to JS", () => testWithFixture("math/addition/add.rock", "JS"))
  test("addBooleanLiteral.rock converted to JS", () => testWithFixture("math/addition/addBooleanLiteral.rock", "JS"))
  test("addBooleanVariable.rock converted to JS", () => testWithFixture("math/addition/addBooleanVariable.rock", "JS"))
  test("addMysteriousLiteral.rock converted to JS", () => testWithFixture("math/addition/addMysteriousLiteral.rock", "JS"))
  test("addMysteriousVariable.rock converted to JS", () => testWithFixture("math/addition/addMysteriousVariable.rock", "JS"))
  test("addToBooleanLiteral.rock converted to JS", () => testWithFixture("math/addition/addToBooleanLiteral.rock", "JS"))
  test("addToBooleanVariable.rock converted to JS", () => testWithFixture("math/addition/addToBooleanVariable.rock", "JS"))
  test("addToMysteriousLiteral.rock converted to JS", () => testWithFixture("math/addition/addToMysteriousLiteral.rock", "JS"))
  test("addToMysteriousVariable.rock converted to JS", () => testWithFixture("math/addition/addToMysteriousVariable.rock", "JS"))
})

describe("decrement", () => {
  test("decrement.rock converted to JS", () => testWithFixture("math/decrement/decrement.rock", "JS"))
  test("decrementBooleanLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementBooleanLiteral.rock", "JS"))
  test("decrementFloatLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementFloatLiteral.rock", "JS"))
  test("decrementIntegerLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementIntegerLiteral.rock", "JS"))
  test("decrementMysteriousLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementMysteriousLiteral.rock", "JS"))
  test("decrementMysteriousVariable.rock converted to JS", () => testWithFixture("math/decrement/decrementMysteriousVariable.rock", "JS"))
  test("decrementNullLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementNullLiteral.rock", "JS"))
  test("decrementStringLiteral.rock converted to JS", () => testWithFixture("math/decrement/decrementStringLiteral.rock", "JS"))
  test("decrementStringVariable.rock converted to JS", () => testWithFixture("math/decrement/decrementStringVariable.rock", "JS"))
})

describe("division", () => {
  test("divide.rock converted to JS", () => testWithFixture("math/division/divide.rock", "JS"))
  test("divideBooleanLiteral.rock converted to JS", () => testWithFixture("math/division/divideBooleanLiteral.rock", "JS"))
  test("divideBooleanVariable.rock converted to JS", () => testWithFixture("math/division/divideBooleanVariable.rock", "JS"))
  test("divideByBooleanLiteral.rock converted to JS", () => testWithFixture("math/division/divideByBooleanLiteral.rock", "JS"))
  test("divideByBooleanVariable.rock converted to JS", () => testWithFixture("math/division/divideByBooleanVariable.rock", "JS"))
  test("divideByMysteriousLiteral.rock converted to JS", () => testWithFixture("math/division/divideByMysteriousLiteral.rock", "JS"))
  test("divideByMysteriousVariable.rock converted to JS", () => testWithFixture("math/division/divideByMysteriousVariable.rock", "JS"))
  test("divideByStringLiteral.rock converted to JS", () => testWithFixture("math/division/divideByStringLiteral.rock", "JS"))
  test("divideByStringVariable.rock converted to JS", () => testWithFixture("math/division/divideByStringVariable.rock", "JS"))
  test("divideByZero.rock converted to JS", () => testWithFixture("math/division/divideByZero.rock", "JS"))
  test("divideMysteriousLiteral.rock converted to JS", () => testWithFixture("math/division/divideMysteriousLiteral.rock", "JS"))
  test("divideMysteriousVariable.rock converted to JS", () => testWithFixture("math/division/divideMysteriousVariable.rock", "JS"))
  test("divideStringLiteral.rock converted to JS", () => testWithFixture("math/division/divideStringLiteral.rock", "JS"))
  test("divideStringVariable.rock converted to JS", () => testWithFixture("math/division/divideStringVariable.rock", "JS"))
})

describe("increment", () => {
  test("increment.rock converted to JS", () => testWithFixture("math/increment/increment.rock", "JS"))
  test("incrementBooleanLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementBooleanLiteral.rock", "JS"))
  test("incrementFloatLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementFloatLiteral.rock", "JS"))
  test("incrementIntegerLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementIntegerLiteral.rock", "JS"))
  test("incrementMysteriousLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementMysteriousLiteral.rock", "JS"))
  test("incrementMysteriousVariable.rock converted to JS", () => testWithFixture("math/increment/incrementMysteriousVariable.rock", "JS"))
  test("incrementNullLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementNullLiteral.rock", "JS"))
  test("incrementStringLiteral.rock converted to JS", () => testWithFixture("math/increment/incrementStringLiteral.rock", "JS"))
  test("incrementStringVariable.rock converted to JS", () => testWithFixture("math/increment/incrementStringVariable.rock", "JS"))
})

describe("multiplication", () => {
  test("multiply.rock converted to JS", () => testWithFixture("math/multiplication/multiply.rock", "JS"))
  test("multiplyBooleanLiteral.rock converted to JS", () => testWithFixture("math/multiplication/multiplyBooleanLiteral.rock", "JS"))
  test("multiplyBooleanVariable.rock converted to JS", () => testWithFixture("math/multiplication/multiplyBooleanVariable.rock", "JS"))
  test("multiplyByBooleanLiteral.rock converted to JS", () => testWithFixture("math/multiplication/multiplyByBooleanLiteral.rock", "JS"))
  test("multiplyByBooleanVariable.rock converted to JS", () => testWithFixture("math/multiplication/multiplyByBooleanVariable.rock", "JS"))
  test("multiplyByMysteriousLiteral.rock converted to JS", () => testWithFixture("math/multiplication/multiplyByMysteriousLiteral.rock", "JS"))
  test("multiplyByMysteriousVariable.rock converted to JS", () => testWithFixture("math/multiplication/multiplyByMysteriousVariable.rock", "JS"))
  test("multiplyMysteriousLiteral.rock converted to JS", () => testWithFixture("math/multiplication/multiplyMysteriousLiteral.rock", "JS"))
  test("multiplyMysteriousVariable.rock converted to JS", () => testWithFixture("math/multiplication/multiplyMysteriousVariable.rock", "JS"))
  test("multiplyStringByNegative.rock converted to JS", () => testWithFixture("math/multiplication/multiplyStringByNegative.rock", "JS"))
})

describe("subtraction", () => {
  test("subtract.rock converted to JS", () => testWithFixture("math/subtraction/subtract.rock", "JS"))
  test("subtractBooleanLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractBooleanLiteral.rock", "JS"))
  test("subtractBooleanVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractBooleanVariable.rock", "JS"))
  test("subtractFromBooleanLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromBooleanLiteral.rock", "JS"))
  test("subtractFromBooleanVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromBooleanVariable.rock", "JS"))
  test("subtractFromMysteriousLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromMysteriousLiteral.rock", "JS"))
  test("subtractFromMysteriousVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromMysteriousVariable.rock", "JS"))
  test("subtractFromStringLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromStringLiteral.rock", "JS"))
  test("subtractFromStringVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractFromStringVariable.rock", "JS"))
  test("subtractMysteriousLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractMysteriousLiteral.rock", "JS"))
  test("subtractMysteriousVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractMysteriousVariable.rock", "JS"))
  test("subtractStringLiteral.rock converted to JS", () => testWithFixture("math/subtraction/subtractStringLiteral.rock", "JS"))
  test("subtractStringVariable.rock converted to JS", () => testWithFixture("math/subtraction/subtractStringVariable.rock", "JS"))
})

describe("simple", () => {
  test("hello.rock converted to JS", () => testWithFixture("simple/hello.rock", "JS"))
  test("sayInput.rock converted to JS", () => testWithFixture("simple/sayInput.rock", "JS"))
})
